Add support for out of bounds area map entries
elluminance/el-crosscode-tweaks pull request #1
Opened 2023-09-28 21:24 UTC by krypciak

2023-10-01 14:02 UTC, EL20202 requested changes
Looks good for the most part! Glad it works as well as it does. I like your clever use of Vec2s, I must say.

However... I did notice one thing when testing an extreme example. If you do a really big offset, the camera won't allow you to scroll and see the whole map. Here's what I used (I had it on a `(-100, -100)` offset. While I don't think most people will go _that_ far - I do think it's possible that larger maps could easily run into this issue (especially if people add maps from both sides). 
[rhombus-sqr.json.patch](https://github.com/EL20202/el-crosscode-tweaks/files/12777296/rhombus-sqr.json.patch)

With that patch above, this is as far as I could scroll to the bottom right.
![image](https://github.com/EL20202/el-crosscode-tweaks/assets/49847844/c257726f-ed46-4e4f-9e62-eb25c7c54c2d)

2023-10-01 14:02 UTC, elluminance commented on src/prestart/menu/custom-map-utils.ts
> +                }
Can be reduced down to either:
```js
for(let y = 0; y < newSize.y; y++) {
    arr[y] = Array(newSize.x).fill(0);
}
```
or even more compactly `const arr = Array.from(Array(newSize.y), () => Array(newSize.x).fill(0))`

2023-10-01 14:02 UTC, elluminance commented on src/prestart/menu/custom-map-utils.ts
> +                console.log(floor, min, max)
Unnecessary `console.log`?

2023-10-01 16:46 UTC, krypciak commented
This should work now, the issue you mentioned required changing the area dimensions
Turns out different floor levels weren't aligned when you resize only one of them, so I resize them all

2024-01-19 00:01 UTC, EL20202 approved these changes

2024-01-19 00:01 UTC, EL20202 commented
Looks like that fixed it! Thanks so much - and sorry it took me so long to check this out.

2024-01-19 00:01 UTC, merged